In [1]:
import pandas as pd
import matplotlib as mlp
import numpy as np

In [7]:
virus_core_dataset = pd.read_csv('C:/Users/kened/OneDrive/Desktop/Estudos/Lean/data/raw/virus_core.csv')
virus_core_dataset

,virus_id,name,family,genus,genome_type,strand,enveloped
0,1,SARS-CoV-2,NaN,Betacoronavirus,RNA,ssRNA(+),True
1,2,Influenza A virus,Orthomyxoviridae,NaN,rna,ssRNA(-),True
2,3,HIV-1,Retroviridae,Lentivirus,RNA,ssRNA-RT,True
3,4,Ebola virus,Filoviridae,Ebolavirus,RNA,ssRNA(-),True
4,5,Zika virus,NaN,Flavivirus,RNA,ssRNA(+),True
...,...,...,...,...,...,...,...
68,69,Arthrobacter phage Agamotto,Unknown,Unknown,Unknown,Unknown,NaN
69,70,Klebsiella phage Kp_AHMU1,Unknown,Unknown,Unknown,Unknown,NaN
70,3,HIV-1,Retroviridae,Lentivirus,RNA,ssRNA-RT,True
71,16,Marburg virus,Filoviridae,Marburgvirus,RNA,ssRNA(-),True
72,41,Escherichia phage ev_rybdy6,Unknown,Unknown,Unknown,Unknown,NaN

In [8]:
virus_epidemiology_dataset = pd.read_csv('C:/Users/kened/OneDrive/Desktop/Estudos/Lean/data/raw/virus_epidemiology.csv')
virus_epidemiology_dataset

    virus_id   transmission  mortality    r0    host
0          1       airborne       2.00  2.50   human
1          2       airborne       0.10  1.30   human
2          3  bodily fluids      80.00  2.00   human
3          4       Airborne        NaN  1.80   human
4          5         vector       0.01  3.00   human
..       ...            ...        ...   ...     ...
67        68  bodily fluids       3.41  1.03    both
68        69       airborne       4.29  1.19  animal
69        70  bodily fluids       7.25  0.75  animal
70         8       airborne       4.10  1.59     NaN
71        34       airborne       6.83  2.71  animal

[72 rows x 5 columns]

In [9]:
virus_target_dataset = pd.read_csv('C:/Users/kened/OneDrive/Desktop/Estudos/Lean/data/raw/virus_target.csv')
virus_target_dataset

    virus_id risk_category
0          1           low
1          2           low
2          3          high
3          4        medium
4          5           low
..       ...           ...
65        66           low
66        67           low
67        68           low
68        69           low
69        70        medium

[70 rows x 2 columns]